name: Executar Testes Automatizados

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar JDK 25
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Compilar código fonte
        run: |
          mkdir -p out
          javac -d out $(find src test -name "*.java")

      - name: Executar testes (classe Main)
        run: |
          cd out
          java org.example.Main
